# Generated by Django 5.2.4 on 2025-07-28 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_phone_number"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="customuser",
            table="user",
        ),
    ]
