# Generated by Django 5.2.4 on 2025-07-30 05:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "db_table": "category",
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        db_column="skill_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="skills.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Skill",
                "verbose_name_plural": "Skills",
                "db_table": "skill",
            },
        ),
        migrations.CreateModel(
            name="Methodology",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "skill",
                    models.ForeignKey(
                        db_column="skill_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="methodologies",
                        to="skills.skill",
                    ),
                ),
            ],
            options={
                "verbose_name": "Methodologies",
                "verbose_name_plural": "Methodologies",
                "db_table": "methodology",
            },
        ),
        migrations.CreateModel(
            name="LearningPath",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "skill",
                    models.ForeignKey(
                        db_column="skill_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_paths",
                        to="skills.skill",
                    ),
                ),
            ],
            options={
                "verbose_name": "LearningPath",
                "verbose_name_plural": "LearningPaths",
                "db_table": "learning_path",
            },
        ),
    ]
